#!/bin/bash

OUTPUT_FILE=m4/plugin_probe.m4
AUTOMAKE_OUTFILE=Plugins.am
PLUGIN_DIR=src/plugins
PLUGIN_ENABLED=
PLUGIN_DIR_ENABLED=
PLUGIN_DISABLED=
PLUGIN_DIR_DISABLED=

echo "Probing for plugins..."

for P in `find $PLUGIN_DIR/* -maxdepth 0 -type d -not -path '*/\.*'`; do
	PNAME=`basename $P`
	if test -e "$P/Makefile.am"; then
		PLUGIN_ENABLED="$PLUGIN_ENABLED $PNAME"
		PLUGIN_DIR_ENABLED="$PLUGIN_DIR_ENABLED $P"
		PLUGIN_MF_ENABLED="$PLUGIN_MF_ENABLED $P/Makefile"
else
		PLUGIN_DISABLED="$PLUGIN_DISABLED $PNAME"
		PLUGIN_DIR_DISABLED="$PLUGIN_DIR_DISABLED $P"
	fi;
done;

# Add NpsGate to the makefile list
PLUGIN_MF_ENABLED="src/Makefile $PLUGIN_MF_ENABLED"

# Replace '/' with '\/' so we can use this variable in sed
PLUGIN_DIR_ENABLED=`echo $PLUGIN_DIR_ENABLED | sed 's/\//\\\\\//g'`
#PLUGIN_MF_ENABLED=`echo $PLUGIN_MF_ENABLED | sed 's/\//\\\\\//g'`

# Build the Makefile.am with all the conditional statements for each plugin
MAKEFILE_AM="### DO NOT EDIT THIS FILE!\n### This file is automatically generated by plugin_probe.sh\nACLOCAL_AMFLAGS=\"-Im4\"\n"
SUBDIRS="\n\nSUBDIRS=src"
for P in $PLUGIN_ENABLED; do
	MAKEFILE_AM="$MAKEFILE_AM\nif ${P}_ENABLED\n${P}_DIR = $PLUGIN_DIR/$P\nendif";
	SUBDIRS="$SUBDIRS \$(${P}_DIR)";
done;
MAKEFILE_AM="$MAKEFILE_AM $SUBDIRS"

# Write the Makefile.am
echo -e $MAKEFILE_AM > $AUTOMAKE_OUTFILE

# Update AC_OUTPUT in configure.ac
AMCOND="
AC_DEFUN([NPSGATE_MAKEFILES], [\n\t
	AC_CONFIG_FILES([$PLUGIN_MF_ENABLED])\n
])\n\n"
#sed -i.bak "s/AC_OUTPUT\\(.*)\\)/AC_OUTPUT([$PLUGIN_MF_ENABLED])/g" configure.ac

AMCOND="$AMCOND\nAC_DEFUN([NPSGATE_PLUGIN_PROBE], ["
for P in $PLUGIN_ENABLED; do
AMCOND="$AMCOND\n\t
	AC_MSG_CHECKING([plugin $P])\n
	NPSGATE_PLUGIN_DISABLE_LIST([$P])
	AC_ARG_ENABLE([$P],\n\t\t
			AS_HELP_STRING([--enable-${P}],\n\t\t
			[build $P plugin [default=yes]]),\n\t\t
			[if test \"\$enableval\" = \"yes\"; then\n\t\t\t
				want_${P}=\"yes\";\n\t\t
			else\n\t\t\t
				want_${P}=\"no\";\n\t\t
			fi])\n\t\t
	if test \"\$want_${P}\" = \"yes\"; then\n\t\t
		ENABLED_PLUGINS=\"\$ENABLED_PLUGINS $P\";
		AC_MSG_RESULT([enabled]);\n\t\t
	else\n\t\t
		DISABLED_PLUGINS=\"\$DISABLED_PLUGINS $P\";\n\t\t
		AC_MSG_RESULT([disabled]);\n\t\t
	fi\n\t
	AM_CONDITIONAL([${P}_ENABLED], [test x\$want_${P} = xyes])" 
done;

AMCOND="$AMCOND\n])"

echo -e $AMCOND > m4/plugin_probe.m4

echo
echo "Detected the following AutoMake enabled plugins:"
for P in $PLUGIN_ENABLED; do
	echo "    $P"
done;

echo
echo "Detected the following non-AutoMake enabled plugins:"
echo "NOTE: These plugins will not be automatically built."
for P in $PLUGIN_DISABLED; do
	echo "    $P"
done;

echo
echo
